services:
  kubernetes-chat:
    build:
      context: .
      dockerfile: Dockerfile.kind
    container_name: kubernetes-kind-agent
    ports:
     - "8501:8501"
     - "8000:8000"
    volumes:
    #  - ~/.kube:/root/.kube:ro
    - ~/.kube:/home/appuser/.kube:ro
    # - ./data:/app/data
    - ./data:/home/appuser/app/data
    environment:
      - KUBECONFIG=/home/appuser/.kube-writable/config
    restart: unless-stopped
    env_file:
      - .env.kind
    healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
     interval: 10s
     timeout: 5s
     retries: 5
    networks:
     - kind

networks: 
 kind:
   external: true