version: '3.8'

services:
  kubernetes-chat:
    build: .
    container_name: kubernetes-agent
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # K8s MCP server
      - "8001:8001"  # K8s health
      - "8010:8010"  # S3 MCP server
      - "8011:8011"  # S3 health
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - MCP_SERVER_URL=http://localhost:8000/mcp
    volumes:
      - chat_data:/app/data        # Persist SQLite DB
      - ~/.kube:/root/.kube:ro     # kubeconfig (if needed)
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    env_file:
      - .env.aws
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - k8s_agent_net

volumes:
  chat_data:

networks:
  k8s_agent_net:
    name: k8s_agent_net