# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: '3.8'

services:
  k8s-mcp:
    build: .
    container_name: k8s-mcp
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - CONTAINER_TYPE=k8s
      - KUBECONFIG=/home/appuser/.kube-writable/config
      - AWS_CONFIG_FILE=/home/appuser/.aws/config.bkp
      - AWS_SHARED_CREDENTIALS_FILE=/home/appuser/.aws/credentials
    volumes:
      - ~/.kube:/home/appuser/.kube:ro
      - ./data:/home/appuser/app/data
      - ~/.aws:/home/appuser/.aws:ro
      - ~/.aws/credentials:/home/appuser/.aws/credentials:ro
      - ~/.aws/config.bkp:/home/appuser/.aws/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - k8s_agent_net
    entrypoint: ["/home/appuser/entrypoint.sh"]

  s3-mcp:
    build: .
    container_name: s3-mcp
    ports:
      - "8010:8010"
      - "8011:8011"
    environment:
      - CONTAINER_TYPE=s3
      - AWS_CONFIG_FILE=/home/appuser/.aws/config.bkp
      - AWS_SHARED_CREDENTIALS_FILE=/home/appuser/.aws/credentials
    env_file:
      - .env.aws
    volumes:
      - ~/.aws:/home/appuser/.aws:ro
      - ./data:/home/appuser/app/data
      - ~/.aws/credentials:/home/appuser/.aws/credentials:ro
      - ~/.aws/config.bkp:/home/appuser/.aws/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8011/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - k8s_agent_net
    entrypoint: ["/home/appuser/entrypoint.sh"]

  kubernetes-chat:
    build: .
    container_name: kubernetes-chat
    ports:
      - "8501:8501"
    depends_on:
      k8s-mcp:
        condition: service_healthy
      s3-mcp:
        condition: service_healthy
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - MCP_SERVER_URL=http://k8s-mcp:8000/mcp
      - AWS_S3_MCP_URL=http://s3-mcp:8010/mcp
      # - KUBECONFIG=/home/appuser/.kube-writable/config
      # - AWS_CONFIG_FILE=/home/appuser/.aws/config.bkp
      # - AWS_SHARED_CREDENTIALS_FILE=/home/appuser/.aws/credentials
    volumes:
      - ./data:/home/appuser/app/data
      - ~/.kube:/home/appuser/.kube:ro
    restart: unless-stopped
    env_file:
      - .env.aws
    networks:
      - k8s_agent_net
    entrypoint: ["/home/appuser/entrypoint.sh"]

networks:
  k8s_agent_net:
    name: k8s_agent_net
